#!/usr/bin/env python3
"""Record and explicitly ignore newly created signature artifacts over 5MB."""
from pathlib import Path
import hashlib,json,subprocess
ROOT=Path(__file__).resolve().parents[2]
# Use find per repository retention rule; skip .git internal objects.
raw=subprocess.check_output(['find','.', '-path','./.git','-prune','-o','-type','f','-size','+5000000c','-print0'],cwd=ROOT)
records=[]
for item in raw.split(b'\0'):
 if not item:continue
 rel=Path(item.decode());p=ROOT/rel
 if not str(rel).startswith('work/signature/'):continue
 h=hashlib.sha256()
 with p.open('rb') as f:
  while chunk:=f.read(1024*1024):h.update(chunk)
 records.append({'path':str(rel),'absolute_path':str(p),'bytes':p.stat().st_size,'sha256':h.hexdigest(),'source_url':None,'source':'locally generated by evidence/signature/run_experiment.py; enospc-loop.img by recorded mkfs/udisks attempt; no download URL'})
records.sort(key=lambda x:x['path'])
(ROOT/'evidence/signature/large_files.json').write_text(json.dumps(records,ensure_ascii=False,indent=2)+'\n')
p=ROOT/'.gitignore';s=p.read_text();marker='\n# stage2b现场签名实验的大文件（find检查；哈希/来源见docs/downloads.md）。\n'
if marker in s:s=s.split(marker)[0]
s+=marker+'\n'.join('/'+x['path'] for x in records)+'\n';p.write_text(s)
p=ROOT/'docs/downloads.md';s=p.read_text();marker='\n## stage2b 压缩器源码与本地签名实验材料\n'
if marker in s:s=s.split(marker)[0]
s+=marker+'\n来源详情见evidence/signature/source_provenance.json；GNU官方release主站请求超时，GNU镜像与Ubuntu orig档取得的1.12原始release归档字节相同。没有取最新master替代。\n\n|本地路径|字节数|sha256|来源URL|\n|---|---:|---|---|\n'
for x in json.loads((ROOT/'evidence/signature/source_provenance.json').read_text())['downloads']:
 s+=f'|{x["path"]}|{x["bytes"]}|{x["sha256"]}|{x["url"]}|\n'
s+='\nGNU源码原样摘录在evidence/src_snapshot/gzip-1.12/，Ubuntu相关补丁原样快照在evidence/src_snapshot/gzip-ubuntu-1.12-1ubuntu3.2/；SOURCE.txt记录来源/版本/时间，manifest.json记录逐文件SHA。完整源码包保留downloads/src/，不入Git。\n\n以下是本地生成且超过5,000,000字节的所有stage2b产物，find已扫描；全部位于被忽略的work/signature/且再显式加入.gitignore。没有来源下载URL，不能虚构。对照JSON还包含每个本地绝对路径：evidence/signature/large_files.json。\n\n|本地路径|字节数|sha256|来源URL/生成方式|\n|---|---:|---|---|\n'
for x in records:s+=f'|{x["path"]}|{x["bytes"]}|{x["sha256"]}|无；真实压缩器/随机输入/tar/loop实验本地产物，方法见docs/signature_experiment.md|\n'
p.write_text(s)
print('Recorded and ignored',len(records),'large signature files;',sum(x['bytes'] for x in records),'bytes')
